module.exports = {
  LOAD_ASSIGNMENTS:  'LOAD_ASSIGNMENTS',
  LOAD_ASSIGNMENTS_SUCCESS: 'LOAD_ASSIGNMENTS_SUCCESS',
  LOAD_ASSIGNMENTS_FAIL: 'LOAD_ASSIGNMENTS_FAIL',
  ADD_ASSIGNMENT: 'ADD_ASSIGNMENT',
  ADD_ASSIGNMENT_SUCCESS: 'ADD_ASSIGNMENT_SUCCESS',
  ADD_ASSIGNMENT_FAIL: 'ADD_ASSIGNMENT_FAIL',
  LOAD_NODES:  'LOAD_NODES',
  LOAD_NODES_SUCCESS: 'LOAD_NODES_SUCCESS',
  LOAD_NODES_FAIL: 'LOAD_NODES_FAIL',
  ADD_NODE: 'ADD_NODE',
  ADD_NODE_SUCCESS: 'ADD_NODE_SUCCESS',
  ADD_NODE_FAIL: 'ADD_NODE_FAIL'
}