module.exports = {
  LOAD_NODES:  'LOAD_NODES',
  LOAD_NODES_SUCCESS: 'LOAD_NODES_SUCCESS',
  LOAD_NODES_FAIL: 'LOAD_NODES_FAIL',
  ADD_NODE: 'ADD_NODE',
  ADD_NODE_SUCCESS: 'ADD_NODE_SUCCESS',
  ADD_NODE_FAIL: 'ADD_NODE_FAIL'
}